/* Generated by conf.py at build time. Do not edit. */
window.__FEATHER_DOCS = {"baseUrl": "https://docs.feather.dev", "currentVersion": "0.2.0", "versionsUrl": "https://docs.feather.dev/versions.json"};
