/* Generated by conf.py at build time. Do not edit. */
window.__FEATHER_DOCS = {"baseUrl": "https://featherinc.github.io/featherdocs_v1", "currentVersion": "0.1.7", "versionsUrl": "https://featherinc.github.io/featherdocs_v1/versions.json"};
